name: flutter_input_kit_example
description: Demo form for flutter_input_kit.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_input_kit:
    path: ../
  flutter_page_kit: ^1.0.0
  flutter_scale_kit: ^2.0.2
  flutter_scale_theme_kit: ^1.0.3
  lemsa_core_kit: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
