name: flutter_input_kit_example
description: Demo form for flutter_input_kit.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_input_kit:
    path: ../
  flutter_page_kit:
    path: ../../flutter_page_kit
  flutter_scale_kit:
    path: ../../flutter_scale_kit
  flutter_scale_theme_kit:
    path: ../../flutter_scale_theme_kit
  lemsa_core_kit:
    path: ../../lemsa_core_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
